/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error-container": "#ffdad6",
        "on-surface": "#1e1b18",
        "on-secondary-fixed-variant": "#3c4b3a",
        outline: "#807663",
        "on-tertiary-fixed-variant": "#4f471b",
        "surface-dim": "#e0d9d4",
        "inverse-on-surface": "#f7efea",
        "on-background": "#1e1b18",
        "on-error": "#ffffff",
        "surface-container-low": "#faf2ed",
        "on-primary": "#ffffff",
        "surface-tint": "#775a00",
        "primary-container": "#c59b27",
        "surface-container": "#f4ece7",
        "primary-fixed-dim": "#eec14b",
        "tertiary-container": "#ada16d",
        "inverse-primary": "#eec14b",
        "on-primary-fixed-variant": "#5a4300",
        "on-tertiary-container": "#3f370d",
        surface: "#fff8f4",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#d4c78f",
        "on-secondary-container": "#586755",
        "inverse-surface": "#33302d",
        primary: "#775a00",
        "on-tertiary": "#ffffff",
        "surface-container-highest": "#e8e1dc",
        "secondary-fixed": "#d7e7d1",
        "surface-variant": "#e8e1dc",
        tertiary: "#685e31",
        background: "#fff8f4",
        "surface-bright": "#fff8f4",
        "outline-variant": "#d1c5af",
        error: "#ba1a1a",
        "tertiary-fixed": "#f1e3a9",
        "primary-fixed": "#ffdf98",
        "on-primary-fixed": "#251a00",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed": "#211b00",
        "secondary-fixed-dim": "#bbcbb6",
        "on-surface-variant": "#4e4635",
        "on-secondary-fixed": "#111f11",
        "surface-container-high": "#eee7e2",
        secondary: "#536251",
        "on-error-container": "#93000a",
        "secondary-container": "#d4e4ce",
        "on-primary-container": "#473500",
      },
      borderRadius: { DEFAULT: "1rem", lg: "2rem", xl: "3rem", full: "9999px" },
      spacing: {
        margin: "3rem",
        "margin-mobile": "1.25rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.75rem",
        "space-xl": "3rem",
        gutter: "1.5rem",
        "gutter-mobile": "1rem",
      },
      fontFamily: {
        "display-lg": ["Playfair Display", "serif"],
        "display-lg-mobile": ["Playfair Display", "serif"],
        "headline-lg": ["Playfair Display", "serif"],
        "headline-lg-mobile": ["Playfair Display", "serif"],
        "headline-md": ["Playfair Display", "serif"],
        "headline-sm": ["Playfair Display", "serif"],
        "title-lg": ["Plus Jakarta Sans", "sans-serif"],
        "title-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Plus Jakarta Sans", "sans-serif"],
        "label-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["56px", { lineHeight: "64px", letterSpacing: "-0.02em", fontWeight: "400" }],
        "display-lg-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", letterSpacing: "0", fontWeight: "400" }],
        "headline-md": ["28px", { lineHeight: "36px", fontWeight: "500" }],
        "headline-sm": ["22px", { lineHeight: "30px", fontWeight: "500" }],
        "title-lg": ["18px", { lineHeight: "26px", letterSpacing: "0.01em", fontWeight: "600" }],
        "title-md": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "26px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "22px", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "label-lg": ["13px", { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "600" }],
        "label-md": ["11px", { lineHeight: "14px", letterSpacing: "0.12em", fontWeight: "600" }],
        "label-sm": ["10px", { lineHeight: "12px", letterSpacing: "0.14em", fontWeight: "700" }],
      },
      keyframes: {
        fadeUp: {
          "0%": { opacity: 0, transform: "translateY(12px)" },
          "100%": { opacity: 1, transform: "translateY(0)" },
        },
      },
      animation: { "fade-up": "fadeUp 0.6s ease-out both" },
    },
  },
  plugins: [],
};